### ISSUE TITLE
How to get the pp of the map with mods?

### ISSUE THREAD

**Issue by jamuwu** [Francesco149/pyttanko#2]
I've been trying to figure this out, but I can't seem to get it to work.
This returns the pp for score except with nomod but I'd assume it would be with the mods since I declare mods as the number provided by the osu api
```python
    stars = pyttanko.diff_calc().calc(bmap)
    pp, _, _, _, _ = pyttanko.ppv2(stars.aim, stars.speed, bmap=bmap, mods=int(mods), n300=int(n300), n100=int(n100), n50=int(n50), nmiss=int(nmiss), combo=int(combo))
```
I thougt maybe doing something like this would work
```python
    speed_mul, _, _, _, _ = pyttanko.mods_apply(mods)
    stars = pyttanko.diff_calc().calc(bmap, speed_mul)
    pp, _, _, _, _ = pyttanko.ppv2(stars.aim, stars.speed, bmap=bmap, mods=int(mods), n300=int(n300), n100=int(n100), n50=int(n50), nmiss=int(nmiss), combo=int(combo))
```
but that just gives errors
 am I missing something not there

**Comment by Francesco149** [comment]
you need to provide mods to both diff_calc and ppv2

**Comment by Francesco149** [comment]
from pydoc:

![](http://hnng.moe/f/UGJ)

**Comment by jamuwu** [comment]
another instance of stupidity on my end rip sorry
