### ISSUE TITLE
Remade version

### ISSUE THREAD

**Issue by The-CJ** [Francesco149/pyttanko#8]
Hey there, i may or may not remade your code in a more object oriented way.
Would be cool if you can include to the description as a alternative.. (if you like)

Also, another question, im not so active in osu anymore,
i heard there will be another pp rework?
if thats true, are you going to implement it as well into the code, so i may can add it to the python lib.

**Comment by The-CJ** [comment]
2 Things:

1st: i i did not made a speed test, (could not get it running / was to lazy), but its not really ment to speed

2nd: i may forgot to link to the project, because im an idiot:
 https://github.com/The-CJ/oppadc.py

**Comment by Francesco149** [comment]
hey, thats pretty cool - while I'm more for not overdoing OOP it's nice to see i inspired a project

yeah i heard there's pp rework inc, i will take a look at it when I can, for now I'm busy with other stuff
